# General options for all profiles.
spring:
  session:
    store-type: hash_map
  profiles:
    active: development #Change this value to production when before building deploying artifact.
  config:
    location:
security:
  basic:
    enabled: false

---
#Production settings.
spring:
    profiles: production
deezer:
  redirect_url: http://api.76room.tk/signin/deezer/step2
  perms: basic_access,email,offline_access,manage_library,listening_history

---
#Development settings.
spring:
    profiles: development
deezer:
  redirect_url: http://127.0.0.1:8080/signin/deezer/step2
  perms: basic_access,email,offline_access,manage_library,listening_history

